### ISSUE TITLE
Update fehlgeschlagen

### ISSUE THREAD

**Issue by mpfingsten** [Studio-Link/webapp#37]
Hallo Sebastian,

ich habe bei mein Studio-Connect über die Weboberfläche das Update gestartet.

Dann ist das Fenster beim 10% Fortschritt für über 10 Minuten stehen geblieben. Das kam mir sehr spanisch vor. Spannung aus / ein hat nichts gebracht. 

Aktueller Status:
Studioconnect meldet sich bei der Fritzbox an und bekommt eine IP zugewiesen. Das Webinterface kann ich aber darüber nicht erreichen.

VG Maik

**Comment by sreimers** [comment]
Moin Maik,

also es kann durchaus je nach Internetverbindung 15-30min dauern.
http://studio-link.de/handbuch.html#updates

Für deinen jetzigen Zustand musst du nun einmal über SSH (Default PW: studio) rein:

$ ssh studio@IP-Adresse
$ sudo su
$ curl -L https://raw.githubusercontent.com/studio-link/images/15.1.0-beta/bootstrap.sh | bash -x

**Comment by sreimers** [comment]
Ich prüfe mal ob ich den Aktivitätsstatus in der nächsten Versionen verbessern kann.

**Comment by mpfingsten** [comment]
hm, der Login ist drei mal fehlgeschlagen. jetzt komme ich per ssh gar nicht mehr ran ...

**Comment by mpfingsten** [comment]
ssh: connect to host (myIP) port 22: Operation timed out

**Comment by sreimers** [comment]
Hattest du das Standard Passwort evtl. geändert? Die Weboberfläche und der SSH Login teilen sich das gleiche Passwort. Nach einem Neustart sollte SSH aber wiederkommen. Gesperrt werden fehlerhafte Versuche eigentlich nicht.

**Comment by mpfingsten** [comment]
nee, pw habe ich nicht geändert

**Comment by mpfingsten** [comment]
aha, jetzt bekomme ich diese Antwort: 

ssh: connect to host (myIP) port 22: Host is down

**Comment by sreimers** [comment]
Hat sich vielleicht die IP Adresse geändert?

Ansonsten läuft es wohl auf ein Clean-Install hinaus. Evtl. ist das Update an einer sehr ungünstigen Stelle abgebrochen. Dazu kannst du dir folgendes Rescue Image laden:

http://repo.studio-link.de/build.img.zip

Entpacken und auf eine SD-Karte schieben:

$ sudo dd bs=1m if=build.img of=/dev/diskn

Hier steht ganz gut beschrieben wie du die SD-Karte findest und vorher umountest unter OSX:

http://www.raspberrypi.org/documentation/installation/installing-images/mac.md

Alternativ kann ich dir anbieten auch per Teamviewer zu helfen.

Anschließend sollte beim Neustart das System über die eingelegte SD-Karte booten. Und der SSH Zugang lautet (User/Passwort): root/root

Dort dann:
```
pacman -Syu wget dosfstools
cd /root
wget http://archlinuxarm.org/os/omap/BeagleBone-bootloader.tar.gz
wget http://archlinuxarm.org/os/ArchLinuxARM-am33x-latest.tar.gz
mkdir boot
mkdir root
mkfs.vfat -F 16 /dev/mmcblk1p1
mkfs.ext4 /dev/mmcblk1p2
mount /dev/mmcblk1p1 boot
mount /dev/mmcblk1p2 root
tar -xvf BeagleBone-bootloader.tar.gz -C boot
tar -xf ArchLinuxARM-am33x-latest.tar.gz -C root
umount boot
umount root
sync
poweroff
```

Nun die SD-Karte entfernen und wieder Einschalten. Dann solltest du wieder über SSH (root/root) reinkommen und:
```
curl -L https://raw.githubusercontent.com/studio-link/images/15.1.0-beta/bootstrap.sh | bash -x
```

**Comment by mpfingsten** [comment]
Mist, habe ich mir schon gedacht. Werde ich mich dem die Tage mal widmen. 

Danke dir für deinen schnellen Support. Melde mich, wenn es Neuigkeiten gibt.

**Comment by sreimers** [comment]
Ok versuche das ganze noch zu vereinfachen indem das Rescue Image dir auch die letzten Schritte abnimmt. Versuche das mal heute Abend vorzubereiten. Ich schicke dir dann den Download Link.

**Comment by sreimers** [comment]
Danke für deinen Test, ich habe die Update-Seite nun ein wenig überarbeitet:
https://sendegate.de/t/studio-link-release-15-1-0-beta/940/3?u=studiolink

**Comment by sreimers** [comment]
Moin Maik,

so habe nun das ganze etwas vereinfacht:
```
http://repo.studio-link.de/build-15_1_0-beta.img.zip
```
Entpacken und auf eine SD-Karte schieben:
```
$ sudo dd bs=1m if=build.img of=/dev/diskn
```
Hier steht ganz gut beschrieben wie du die SD-Karte findest und vorher umountest unter OSX:
```
http://www.raspberrypi.org/documentation/installation/installing-images/mac.md
```
Die SD Karte dann einfach vor dem Einschalten einlegen und ca. 10min warten. Die Installation startet automatisch und wenn alles fertig ist gehen die Lichter vorne aus.

Dann kannst du die Karte entfernen und neu starten. Du musst dann allerdings noch einmal
den Update Prozess für das Provisioning kurz durchlaufen lassen, einfach im Browser:
```
[URL]/system/upgrade/15.1.0-beta
```

**Comment by timpritlove** [comment]
Habe das mal getestet. Sieht nicht so aus, als ob die Installation automatisch startet. Die Lampen gehen nie aus und die URL /system/upgrade/15.1.0-beta liefert nur "Ups, site not found!". 

Muss man noch irgendwas tun, damit das Gerät vom SD bootet?

**Comment by sreimers** [comment]
Hi Tim,

probier mal den Boot Switch S2 während des Einschaltens zu drücken (wenn die LEDs einmal alle an waren und wieder ausgehen kannst du loslassen). Ob die Installation angelaufen ist kannst du über SSH feststellen. Du solltest dich mit root/root ins Rescue einloggen können.

**Comment by timpritlove** [comment]
hm, die 4 LEDS gehen nicht an, wenn ich S2 gedrückt halte beim Einschalten. Gerät meldet auch kein SSH auf dem Netz via Bonjour.

**Comment by sreimers** [comment]
Dann wird vermutlich der Bootloader auf der SD-Karte nicht gefunden. Kannst du mal schauen ob die SD-Karte korrekt beschrieben wurde? Müssten zwei Partitionen drauf sein, eine 64MByte FAT16 und eine größere EXT4. Ansonsten noch einmal drüber bügeln.

**Comment by timpritlove** [comment]
Ah, ich habe das Image direkt auf eine Partition geschrieben, nicht auf die komplette SD. Melde mich zurück wenn ich das neu geschrieben habe.

**Comment by timpritlove** [comment]
Okay, hat geklappt.
